export const FB2_GENRES: Record<string, string> = {
  adventure_fantasy: 'Приключения: Фэнтези',
  aphorisms: 'Афоризмы',
  aphorism_quote: 'Афоризмы и Цитаты',
  back_to_ussr: 'Возвращение в СССР',
  boyar_anime: 'Бояръ-аниме',
  prose_military: 'Военная проза',
  sci_economy: 'Научная экономика',
  architecture: 'Архитектура',
  economics: 'Экономика',
  dark_fantasy: 'Тёмное Фэнтези',
  cinema_theatre: 'Кино и Театр',
  'epic-fantasy': 'Эпичечное Фэнтези',
  sf_history: 'Альтернативная история',
  sf_action: 'Боевая Фантастика',
  sf_epic: 'Эпическая Фантастика',
  sf_heroic: 'Героическая фантастика',
  sf_cyberpunk: 'Киберпанк',
  sf_space: 'Космическая Фантастика',
  sf_social: 'Социальная фантастика',
  sf_horror: 'Ужасы и Мистика',
  sf_humor: 'Юмористическая фантастика',
  sf_fantasy: 'Научное Фэнтези',
  sf_litrpg: 'ЛитРПГ: Фантастика',
  city_fantasy: 'Городское Фэнтези',
  sf_mystic: 'Мистика',
  sf: 'Научная Фантастика',
  child_sf: 'Детская Фантастика',
  det_classic: 'Классический Детектив',
  det_police: 'Полицейский Детектив',
  det_action: 'Боевики',
  det_irony: 'Иронический Детектив',
  det_history: 'Исторический Детектив',
  det_espionage: 'Шпионский Детектив',
  det_crime: 'Криминальный Детектив',
  det_political: 'Политический Детектив',
  det_maniac: 'Маньяки',
  det_rus: 'Детская Русккая Проза',
  det_hard: 'Крутой Детектив',
  dragon_fantasy: 'Книги о Драконах',
  essay: 'Эссе',
  essays: 'Эссе',
  foreign_detective: 'Зарубежный Детектив',
  foreign_adventure: 'Зарубежные Приключения',
  foreign_children: 'Зарубежная Детская Литература',
  foreign_fantasy: 'Зарубежное Фэнтези',
  foreign_contemporary: 'Зарубежная Современная Литература',
  foreign_publicism: 'Зарубежная Публицистика',
  foreign_sf: 'Зарубежная Фантастика',
  foreign_love: 'Зарубежные Любовные Романы',
  fantasy_fight: 'Боевое Фэнтези',
  fantasy_dark: 'Темное Фэнтези',
  fantasy_action: 'Боевая Фэнтези',
  'fantasy-action': 'Боевая Фэнтези',
  fanfiction: 'Фанфики',
  foreign_edu: 'Зарубежная Учебная Литература',
  great_story: 'Великие Истории',
  humor_fantasy: 'Юмористическое Фэнтези',
  historical_fantasy: 'Исторические Фэнтези',
  'heroic-fantasy': 'Героическое Фэнтези',
  thriller: 'Триллеры',
  detective: 'Детектив',
  sf_detective: 'Детективная Фантастика',
  child_det: 'Детские Остросюжетные',
  prose: 'Проза',
  prose_classic: 'Классическая Проза',
  prose_history: 'Историческая Проза',
  prose_contemporary: 'Современная Проза',
  prose_counter: 'Контркультура',
  prose_rus_classic: 'Русская Классика',
  prose_su_classics: 'Советская Классика',
  psy_childs: 'Детская Психология',
  psy_personal: 'Психология',
  psy_theraphy: 'Психотерапия',
  psy_sex_and_family: 'Психология Семьи и Половых Отношений',
  psy_generic: 'Психология',
  humor_prose: 'Юмористическая Проза',
  child_prose: 'Детская Проза',
  love: 'Любовные романы',
  love_contemporary: 'Современные Любовные Романы',
  love_history: 'Исторические Любовные Романы',
  love_detective: 'Остросюжетные Любовные Романы',
  love_short: 'Короткие Любовные Романы',
  love_erotica: 'Эротика',
  love_fantasy: 'Фантастические Любовные Романы',
  love_sf: 'Фантастические Любовные Романы',
  love_sf_fantasy: 'Фэнтези: Любовные Романы',
  magician_book: 'Книги о Волшебниках',
  literature_18: 'Литература XVIII века',
  literature_19: 'Литература XIX века',
  literature_20: 'Литература XX века',
  literature_21: 'Литература XXI века',
  literature_books: 'Книги',
  literature_short: 'Короткая Проза',
  litrpg: 'ЛитРПГ',
  network_literature: 'Online Литература',
  narrative: 'Повествование',
  novel: 'Роман',
  adv_western: 'Вестерны',
  adv_history: 'Исторические Приключения',
  adv_indian: 'Приключения: Индейцы',
  adv_maritime: 'Морские Приключения',
  adv_geo: 'Путешествия и География',
  adv_animal: 'Природа и Животные',
  adventure: 'Приключения',
  child_adv: 'Детские Приключения',
  children: 'Детское',
  child_tale: 'Сказки',
  child_verse: 'Детские Стихи',
  child_education: 'Детская Образовательная литература',
  other: 'Другое',
  poetry: 'Поэзия',
  popadanec: 'Попаданец',
  popadantsy: 'Попаданцы',
  popadancy: 'Попаданцы',
  'popadantsy-v-magicheskie-miry': 'Попаданцы в магические миры',
  popadantsy_vo_vremeni: 'Попаданцы во Времени',
  prose_magic: 'Магическая Проза',
  dramaturgy: 'Драматургия',
  humor_verse: 'Юмористические Стихи',
  antique_ant: 'Античная Литература',
  antique_european: 'Европейская Старинная Литература',
  antique_russian: 'Древнерусская Литература',
  antique_east: 'Древневосточная Литература',
  antique_myths: 'Мифы. Легенды. Эпос',
  antique: 'Старинная Литература',
  sci_history: 'История',
  sci_psychology: 'Психология',
  sci_culture: 'Культурология',
  sci_religion: 'Религиоведение',
  sci_philosophy: 'Философия',
  sci_politics: 'Политика',
  sci_business: 'Деловая литература',
  sci_juris: 'Юриспруденция',
  sci_linguistic: 'Языкознание',
  sci_medicine: 'Медицина',
  sci_phys: 'Физика',
  sci_math: 'Математика',
  sci_chem: 'Химия',
  sci_biology: 'Биология',
  sci_tech: 'Технические',
  sci_philology: 'Филология',
  'sci-fi': 'Научная Фантастика',
  sci_social_studies: 'Социологические науки',
  sci_popular: 'Научно-популярная Литература',
  sf_etc: 'Фантастика',
  short_story: 'Рассказы',
  science: 'Научно-образовательная Литература',
  sf_fantasy_city: 'Городское Фэнтези',
  sf_rus: 'Русская Фантастика',
  sf_technofantasy: 'Научное Технофэнтези',
  sf_postapocalyptic: 'Пост-апокалиптическая Фантастика',
  comp_www: 'Интернет',
  comp_programming: 'Программирование',
  comp_hard: 'Компьютерное Железо',
  comp_soft: 'Программы',
  comp_db: 'Базы Данных',
  comp_osnet: 'ОС и Сети',
  computers: 'Компьютерная Литература',
  ref_encyc: 'Энциклопедии',
  ref_dict: 'Словари',
  ref_ref: 'Справочники',
  ref_guide: 'Руководства',
  reference: 'Справочная Литература',
  rus_publication: 'Русская Публицистика',
  russian_contemporary: 'Современная Русская Литература',
  russian_fantasy: 'Русское Фэнтези',
  fantasy_rus: 'Русское Фэнтези',
  romance_fantasy: 'Фэнтези: Любовные Романы',
  religion_budda: 'Буддизм',
  nonf_biography: 'Биографии и Мемуары',
  nonf_publicism: 'Публицистика',
  nonf_criticism: 'Критика',
  nonfiction: 'Документальная Литература',
  design: 'Искусство, Дизайн',
  religion: 'Религия',
  religion_rel: 'Религия',
  religion_esoterics: 'Эзотерика',
  religion_self: 'Самосовершенствование',
  humor_anecdote: 'Анекдоты',
  humor: 'Юмор',
  home_cooking: 'Кулинария',
  home_pets: 'Домашние Животные',
  home_crafts: 'Хобби, Ремесла',
  home_entertain: 'Развлечения',
  home_health: 'Здоровье',
  home_garden: 'Сад и Огород',
  home_diy: 'Сделай Сам',
  home_sport: 'Спорт',
  home_sex: 'Эротика, Секс',
  home: 'Дом и Семья',
  vampire_book: 'Книги о Вампирах',
  visual_arts: 'Искусство',
  upbringing_book: 'Учебное пособие по воспитанию',
  unrecognised: 'Непризнанное',
};

export const FB2_GENRES_KEYS_SORTED = Object.keys(FB2_GENRES).sort((a, b) => {
  return FB2_GENRES[a].localeCompare(FB2_GENRES[b]);
});
